In [1]:
import pandas as pd
import pickle

data = pd.read_pickle('dtm_stop.pkl')
data

,aaaaah,aaaaahhhhhhh,aaaaauuugghhhhhh,aaaahhhhh,aaah,aah,abc,abcs,ability,abject,...,zee,zen,zeppelin,zero,zillion,zombie,zombies,zoning,zoo,éclair
ali,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
anthony,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
bill,1,0,0,0,0,0,0,1,0,0,...,0,0,0,1,1,1,1,1,0,0
bo,0,1,1,1,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
dave,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
hasan,0,0,0,0,0,0,0,0,0,0,...,2,1,0,1,0,0,0,0,0,0
jim,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
john,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
louis,0,0,0,0,0,3,0,0,0,0,...,0,0,0,2,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,0,0,2,1,0,0,0,0,0,0
ricky,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,1,0

In [6]:
from gensim import matutils, models
import scipy.sparse

In [7]:
tdm = data.transpose()
tdm.head()

,ali,anthony,bill,bo,dave,hasan,jim,joe,john,louis,mike,ricky
aaaaah,0,0,1,0,0,0,0,0,0,0,0,0
aaaaahhhhhhh,0,0,0,1,0,0,0,0,0,0,0,0
aaaaauuugghhhhhh,0,0,0,1,0,0,0,0,0,0,0,0
aaaahhhhh,0,0,0,1,0,0,0,0,0,0,0,0
aaah,0,0,0,0,1,0,0,0,0,0,0,0

In [8]:
sparse_counts = scipy.sparse.csr_matrix(tdm)
corpus = matutils.Sparse2Corpus(sparse_counts)

In [9]:
cv = pickle.load(open("cv_stop.pkl", "rb"))
id2word = dict((v, k) for k, v in cv.vocabulary_.items())

C:\Users\AIMAN\anaconda3\lib\site-packages\sklearn\base.py:310: UserWarning: Trying to unpickle estimator CountVectorizer from version 0.18.2 when using version 0.24.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(

In [10]:
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=2, passes=10)
lda.print_topics()

[(0,
  '0.009*"fucking" + 0.008*"shit" + 0.007*"fuck" + 0.005*"want" + 0.005*"going" + 0.005*"say" + 0.005*"theyre" + 0.004*"man" + 0.004*"good" + 0.004*"hes"'),
 (1,
  '0.006*"say" + 0.005*"cause" + 0.005*"didnt" + 0.005*"thing" + 0.004*"really" + 0.004*"hes" + 0.004*"id" + 0.004*"theyre" + 0.004*"mean" + 0.004*"little"')]

In [11]:
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=3, passes=10)
lda.print_topics()

[(0,
  '0.007*"fucking" + 0.006*"say" + 0.006*"going" + 0.005*"went" + 0.005*"day" + 0.005*"want" + 0.005*"didnt" + 0.005*"thing" + 0.005*"theyre" + 0.004*"hes"'),
 (1,
  '0.007*"shit" + 0.005*"ok" + 0.005*"lot" + 0.004*"gotta" + 0.004*"wanna" + 0.004*"husband" + 0.004*"cause" + 0.003*"day" + 0.003*"women" + 0.003*"pregnant"'),
 (2,
  '0.009*"fucking" + 0.009*"fuck" + 0.008*"shit" + 0.006*"man" + 0.006*"theyre" + 0.005*"good" + 0.005*"theres" + 0.005*"life" + 0.005*"hes" + 0.005*"didnt"')]

In [12]:
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=4, passes=10)
lda.print_topics()

[(0,
  '0.010*"dad" + 0.007*"going" + 0.006*"want" + 0.006*"love" + 0.005*"shes" + 0.005*"hasan" + 0.005*"say" + 0.004*"life" + 0.004*"mom" + 0.004*"hey"'),
 (1,
  '0.010*"fucking" + 0.007*"went" + 0.007*"say" + 0.006*"day" + 0.005*"going" + 0.005*"thing" + 0.005*"ive" + 0.005*"little" + 0.005*"fuck" + 0.005*"joke"'),
 (2,
  '0.008*"fucking" + 0.008*"fuck" + 0.007*"theyre" + 0.005*"shit" + 0.005*"cause" + 0.005*"say" + 0.005*"house" + 0.005*"man" + 0.005*"little" + 0.004*"real"'),
 (3,
  '0.009*"shit" + 0.006*"fucking" + 0.006*"cause" + 0.006*"didnt" + 0.006*"hes" + 0.005*"fuck" + 0.005*"really" + 0.004*"want" + 0.004*"thing" + 0.004*"life"')]

In [20]:
from nltk import word_tokenize, pos_tag
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

def nouns(text):
    '''Given a string of text, tokenize the text and pull out only the nouns.'''
    is_noun = lambda pos: pos[:2] == 'NN'
    tokenized = word_tokenize(text)
    all_nouns = [word for (word, pos) in pos_tag(tokenized) if is_noun(pos)] 
    return ' '.join(all_nouns)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\AIMAN\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\AIMAN\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger.zip.

In [21]:
data_clean = pd.read_pickle('data_clean.pkl')
data_clean

                                                transcript
ali      ladies and gentlemen please welcome to the sta...
anthony  thank you thank you thank you san francisco th...
bill      all right thank you thank you very much thank...
bo       bo what old macdonald had a farm e i e i o and...
dave     this is dave he tells dirty jokes for a living...
hasan      whats up davis whats up im home i had to bri...
jim         ladies and gentlemen please welcome to the ...
joe         ladies and gentlemen welcome joe rogan  wha...
john     all right petunia wish me luck out there you w...
louis    introfade the music out lets roll hold there l...
mike     wow hey thank you thanks thank you guys hey se...
ricky    hello hello how you doing great thank you wow ...

In [22]:
data_nouns = pd.DataFrame(data_clean.transcript.apply(nouns))
data_nouns

                                                transcript
ali      ladies gentlemen stage ali hi thank hello na s...
anthony  thank thank people i em i francisco city world...
bill     thank thank pleasure georgia area oasis i june...
bo       macdonald farm e i o farm pig e i i snort macd...
dave     jokes living stare work profound train thought...
hasan    whats davis whats home i netflix la york i son...
jim      ladies gentlemen stage mr jim jefferies thank ...
joe      ladies gentlemen joe fuck thanks phone fuckfac...
john     petunia thats hello hello chicago thank crowd ...
louis    music lets lights lights thank i i place place...
mike     wow hey thanks look insane years everyone i id...
ricky    hello thank fuck thank im gon youre weve money...

In [23]:
from sklearn.feature_extraction import text
from sklearn.feature_extraction.text import CountVectorizer

# Re-add the additional stop words since we are recreating the document-term matrix
add_stop_words = ['like', 'im', 'know', 'just', 'dont', 'thats', 'right', 'people',
                  'youre', 'got', 'gonna', 'time', 'think', 'yeah', 'said']
stop_words = text.ENGLISH_STOP_WORDS.union(add_stop_words)

# Recreate a document-term matrix with only nouns
cvn = CountVectorizer(stop_words=stop_words)
data_cvn = cvn.fit_transform(data_nouns.transcript)
data_dtmn = pd.DataFrame(data_cvn.toarray(), columns=cvn.get_feature_names())
data_dtmn.index = data_nouns.index
data_dtmn

,aaaaahhhhhhh,aaaaauuugghhhhhh,aaaahhhhh,aah,abc,abcs,ability,abortion,abortions,abuse,...,yummy,ze,zealand,zee,zeppelin,zillion,zombie,zombies,zoo,éclair
ali,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
anthony,0,0,0,0,0,0,0,2,0,0,...,0,0,10,0,0,0,0,0,0,0
bill,0,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,1,1,1,0,0
bo,1,1,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
dave,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
hasan,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
jim,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
john,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
louis,0,0,0,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,0,0,0
ricky,0,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0

In [26]:
# Create the gensim corpus
corpusn = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmn.transpose()))

# Create the vocabulary dictionary
id2wordn = dict((v, k) for k, v in cvn.vocabulary_.items())

In [27]:
# Let's try 2 topics
ldan = models.LdaModel(corpus=corpusn, num_topics=2, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.009*"life" + 0.009*"shit" + 0.008*"hes" + 0.007*"man" + 0.007*"thing" + 0.007*"cause" + 0.007*"gon" + 0.006*"way" + 0.006*"fuck" + 0.006*"day"'),
 (1,
  '0.011*"day" + 0.009*"thing" + 0.007*"man" + 0.006*"way" + 0.006*"joke" + 0.006*"things" + 0.006*"hes" + 0.005*"shit" + 0.005*"fuck" + 0.005*"lot"')]

In [28]:
# Let's try 3 topics
ldan = models.LdaModel(corpus=corpusn, num_topics=3, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.008*"cause" + 0.008*"point" + 0.007*"kind" + 0.005*"way" + 0.005*"id" + 0.005*"jenny" + 0.005*"night" + 0.005*"car" + 0.005*"guy" + 0.005*"gon"'),
 (1,
  '0.010*"day" + 0.009*"thing" + 0.008*"joke" + 0.007*"way" + 0.007*"things" + 0.007*"man" + 0.006*"house" + 0.006*"kids" + 0.006*"fuck" + 0.006*"life"'),
 (2,
  '0.011*"shit" + 0.009*"life" + 0.009*"man" + 0.009*"thing" + 0.009*"hes" + 0.008*"day" + 0.007*"fuck" + 0.007*"guy" + 0.007*"lot" + 0.006*"way"')]

In [29]:
# Let's try 4 topics
ldan = models.LdaModel(corpus=corpusn, num_topics=4, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.009*"man" + 0.008*"hes" + 0.007*"shit" + 0.007*"dad" + 0.007*"life" + 0.006*"years" + 0.006*"way" + 0.006*"fuck" + 0.006*"thing" + 0.006*"day"'),
 (1,
  '0.014*"life" + 0.011*"thing" + 0.010*"fuck" + 0.010*"shit" + 0.010*"cause" + 0.010*"kids" + 0.009*"man" + 0.008*"hes" + 0.008*"gon" + 0.007*"theyre"'),
 (2,
  '0.012*"day" + 0.010*"thing" + 0.009*"cause" + 0.008*"shit" + 0.007*"guy" + 0.007*"way" + 0.007*"gon" + 0.006*"lot" + 0.006*"hes" + 0.006*"women"'),
 (3,
  '0.000*"day" + 0.000*"life" + 0.000*"cause" + 0.000*"thing" + 0.000*"fuck" + 0.000*"way" + 0.000*"man" + 0.000*"guy" + 0.000*"hes" + 0.000*"girl"')]

In [30]:
def nouns_adj(text):
    '''Given a string of text, tokenize the text and pull out only the nouns and adjectives.'''
    is_noun_adj = lambda pos: pos[:2] == 'NN' or pos[:2] == 'JJ'
    tokenized = word_tokenize(text)
    nouns_adj = [word for (word, pos) in pos_tag(tokenized) if is_noun_adj(pos)] 
    return ' '.join(nouns_adj)

In [31]:
# Apply the nouns function to the transcripts to filter only on nouns
data_nouns_adj = pd.DataFrame(data_clean.transcript.apply(nouns_adj))
data_nouns_adj

                                                transcript
ali      ladies gentlemen welcome stage ali wong hi wel...
anthony  thank san francisco thank good people surprise...
bill     right thank thank pleasure greater atlanta geo...
bo       old macdonald farm e i i o farm pig e i i snor...
dave     dirty jokes living stare most hard work profou...
hasan    whats davis whats im home i netflix special la...
jim      ladies gentlemen welcome stage mr jim jefferie...
joe      ladies gentlemen joe fuck san francisco thanks...
john     right petunia august thats good right hello he...
louis    music lets lights lights thank much i i i nice...
mike     wow hey thanks hey seattle nice look crazy ins...
ricky    hello great thank fuck thank lovely welcome im...

In [32]:
# Create a new document-term matrix using only nouns and adjectives, also remove common words with max_df
cvna = CountVectorizer(stop_words=stop_words, max_df=.8)
data_cvna = cvna.fit_transform(data_nouns_adj.transcript)
data_dtmna = pd.DataFrame(data_cvna.toarray(), columns=cvna.get_feature_names())
data_dtmna.index = data_nouns_adj.index
data_dtmna

,aaaaah,aaaaahhhhhhh,aaaaauuugghhhhhh,aaaahhhhh,aah,abc,abcs,ability,abject,able,...,ze,zealand,zee,zeppelin,zero,zillion,zombie,zombies,zoo,éclair
ali,0,0,0,0,0,1,0,0,0,2,...,0,0,0,0,0,0,1,0,0,0
anthony,0,0,0,0,0,0,0,0,0,0,...,0,10,0,0,0,0,0,0,0,0
bill,1,0,0,0,0,0,1,0,0,1,...,1,0,0,0,0,1,1,1,0,0
bo,0,1,1,1,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
dave,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
hasan,0,0,0,0,0,0,0,0,0,1,...,0,0,2,0,0,0,0,0,0,0
jim,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
john,0,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,1
louis,0,0,0,0,3,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,0,0
ricky,0,0,0,0,0,0,0,1,1,2,...,0,0,0,0,0,0,0,0,1,0

In [33]:
# Create the gensim corpus
corpusna = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmna.transpose()))

# Create the vocabulary dictionary
id2wordna = dict((v, k) for k, v in cvna.vocabulary_.items())

In [34]:
# Let's start with 2 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=2, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.006*"mom" + 0.004*"joke" + 0.004*"parents" + 0.003*"ass" + 0.003*"bo" + 0.003*"um" + 0.003*"hasan" + 0.003*"comedy" + 0.003*"clinton" + 0.003*"guns"'),
 (1,
  '0.003*"joke" + 0.002*"dead" + 0.002*"jenny" + 0.002*"door" + 0.002*"ahah" + 0.002*"nuts" + 0.002*"dick" + 0.002*"young" + 0.002*"gay" + 0.002*"friend"')]

In [35]:
# Let's start with 3 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=3, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.007*"joke" + 0.006*"mom" + 0.004*"bo" + 0.004*"clinton" + 0.004*"repeat" + 0.003*"anthony" + 0.003*"eye" + 0.003*"jokes" + 0.003*"ok" + 0.003*"contact"'),
 (1,
  '0.004*"parents" + 0.004*"hasan" + 0.003*"jenny" + 0.003*"door" + 0.003*"mom" + 0.002*"joke" + 0.002*"minutes" + 0.002*"jenner" + 0.002*"texas" + 0.002*"love"'),
 (2,
  '0.004*"gun" + 0.004*"son" + 0.004*"guns" + 0.004*"ahah" + 0.003*"ass" + 0.003*"dog" + 0.003*"gay" + 0.003*"wife" + 0.003*"tit" + 0.003*"class"')]

In [36]:
# Let's start with 4 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=4, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.004*"gun" + 0.004*"wife" + 0.004*"ass" + 0.004*"jenny" + 0.004*"clinton" + 0.004*"guns" + 0.003*"parents" + 0.003*"friend" + 0.003*"class" + 0.003*"mom"'),
 (1,
  '0.008*"joke" + 0.005*"mom" + 0.004*"jokes" + 0.004*"parents" + 0.004*"hasan" + 0.003*"anthony" + 0.003*"door" + 0.003*"mad" + 0.003*"jenner" + 0.003*"dead"'),
 (2,
  '0.008*"bo" + 0.007*"repeat" + 0.006*"eye" + 0.006*"ok" + 0.005*"contact" + 0.005*"husband" + 0.005*"um" + 0.005*"cos" + 0.004*"brain" + 0.004*"pregnant"'),
 (3,
  '0.007*"ahah" + 0.005*"tit" + 0.005*"gay" + 0.005*"nigga" + 0.005*"young" + 0.004*"ok" + 0.004*"murder" + 0.003*"son" + 0.003*"ha" + 0.003*"date"')]

In [ ]:
# Our final LDA model (for now)
ldana = models.LdaModel(corpus=corpusna, num_topics=4, id2word=id2wordna, passes=80)
ldana.print_topics()

In [ ]:
corpus_transformed = ldana[corpusna]
list(zip([a for [(a,b)] in corpus_transformed], data_dtmna.index))